# Generated by Django 5.0.1 on 2024-01-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DynamicFormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("field_type", models.CharField(max_length=50)),
                (
                    "form_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client_app.formtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client_app.formtype",
                    ),
                ),
            ],
        ),
    ]
