# Generated by Django 5.0.1 on 2024-01-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrequest",
            name="form_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client_app.formtype",
            ),
        ),
    ]
