# Generated by Django 5.0.1 on 2024-01-17 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0002_alter_userrequest_form_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicformfield",
            name="user_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="client_app.userrequest",
            ),
        ),
    ]
