# Generated by Django 5.0.1 on 2024-01-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0004_remove_dynamicformfield_user_request_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dynamicformfield",
            name="form_type",
        ),
        migrations.AddField(
            model_name="dynamicformfield",
            name="form_type",
            field=models.ManyToManyField(to="client_app.formtype"),
        ),
    ]
