# Generated by Django 5.0.1 on 2024-01-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0005_remove_dynamicformfield_form_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicformfieldvalue",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="client_app.dynamicformfield",
            ),
        ),
    ]
