# Generated by Django 5.0.1 on 2024-01-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0006_alter_dynamicformfieldvalue_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicformfieldvalue",
            name="user_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client_app.userrequest",
            ),
        ),
    ]
