# Generated by Django 5.0.1 on 2024-01-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0008_userrequest_completed_userrequest_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicformfieldvalue",
            name="label",
            field=models.CharField(max_length=50),
        ),
    ]
