# Generated by Django 5.0.1 on 2024-01-31 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0009_alter_dynamicformfieldvalue_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approval",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_approvals",
                to="client_app.userrequest",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="signature",
            field=models.TextField(blank=True, null=True),
        ),
    ]
