# Generated by Django 5.0.1 on 2024-02-01 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0010_alter_approval_comment_alter_approval_request_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicformfield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dynamicformfield",
            name="options",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="approval",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_request_approvals",
                to="client_app.userrequest",
            ),
        ),
        migrations.AlterField(
            model_name="dynamicformfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("CharField", "CharField"),
                    ("ChoiceField", "ChoiceField"),
                    ("IntegerField", "IntegerField"),
                    ("DateField", "DateField"),
                    ("EmailField", "EmailField"),
                    ("DecimalField", "DecimalField"),
                    ("BooleanField", "BooleanField"),
                    ("TextField", "TextField"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
